### ISSUE TITLE
vtmgo addon start niet

### ISSUE THREAD

**Issue by Roland1947** [add-ons/plugin.video.vtm.go#324]
**Describe the bug**
vtmgo addon start niet

**To Reproduce**
1.start addon
2.login on https://login2.vtm.be
3. get error

**Expected behavior**

**Screenshots**
![01](https://user-images.githubusercontent.com/92874540/171236359-e86be7bf-3085-4e7c-831f-ed1ba119a5a7.PNG)
![02](https://user-images.githubusercontent.com/92874540/171236377-823430ad-774f-43b7-85ed-d1669e0e51fd.PNG)
![03](https://user-images.githubusercontent.com/92874540/171236397-bd35cbc5-86fd-493e-acf3-69fdb034db61.PNG)

**Logs**
2022-05-31 19:16:05.646 T:4492    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 179, in run
                                                       routing.run(params)
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 25, in index
                                                       show_login_menu()
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 39, in show_login_menu
                                                       Authentication().login()
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\modules\authentication.py", line 49, in login
                                                       check = self._auth.authorize_check()
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 121, in authorize_check
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/vtmgo/tokens', data={
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 70, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 177, in _request
                                                       response.raise_for_status()
                                                     File "C:\Users\Gebruiker\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/tokens
                                                   -->End of Python script error report<--
**System**
 - Addon version: 1.3.0+matrix.1
![04](https://user-images.githubusercontent.com/92874540/171236828-b746fb3c-bdf9-40f7-aa62-d56ce22aa71f.PNG)
 - Kodi version: 19.4
 - Inputstream adaptive version: 190.0.5 by peak3d
 - Operating System Windows
![06](https://user-images.githubusercontent.com/92874540/171238116-928ab57a-ab67-4cc1-9b48-a6eaef6a7f8c.PNG)

 - Special Hardware intel compute stick

**Additional context**

**Comment by wormpy001** [comment]
Same here. Started yesterday

**Comment by Bart80-1** [comment]
Hi, also same here. Log here: [https://paste.kodi.tv/abagoxiqos](https://paste.kodi.tv/abagoxiqos)
Raspberry Pi 4, LibreElec 10.0.2.
I did not try to refresh tokens or something like that.

**Comment by boskabouter007** [comment]
had this problem on my RPI4, with latest Matrix.
Installing this update, fixed my problem.

**Comment by cometoluc** [comment]
New Problem, in vtmgo 
windows1032 bit with the new addon        plugin.video.vtm.go-1.3.1+matrix.1    it first worked. But now i wanted to see something in my menu i get the error 

404 Client Error: Not Found for url:
https://Ifvp-api.dpgmedia.net/vtmgo/programs/043dd3d6-218e4d

please help

**Comment by CasvanDongen** [comment]
> New Problem, in vtmgo windows1032 bit with the new addon plugin.video.vtm.go-1.3.1+matrix.1 it first worked. But now i wanted to see something in my menu i get the error
> 
> 404 Client Error: Not Found for url: https://Ifvp-api.dpgmedia.net/vtmgo/programs/043dd3d6-218e4d
> 
> please help

It could be a cache issue. But just to be sure, what steps did you take when you got this issue? I'll see if I'm able to reproduce it locally.

**Comment by cometoluc** [comment]
i did nothing special, i saw a movie and then when i got to go back to my menu the error was there

**Comment by cometoluc** [comment]
Hello,
i deinstalled vtmgo and reinstalled it with the zipfile
then iget like your first photo on top of the page and there i login with my normal login and then  i go it works agaain on my other pc. So i think that my problem is solved. Sorry for the Helppost i did.

**Comment by cometoluc** [comment]
Hello, i have a serieus problem again with the vtmgo addon

ik work on a windows 10 pc 32bit pc with  kodi 19.3 (19.3.0)
my version of vtmgo is 1.3.0+matrix. 1

sins the update with the zip file all seemd to be alright but i soon found out that ther where other problems.

i already deinstalled vtmgo version with removing settings and then it seemd right again but when i go in the app and look at something in movies it plays. But when i stop in the middle or something to see the rest later i cannot fimd the movie again in movies. Its gone. and a blanc line that i cannot open is on top of the list and the movie is nowhere tho be found.

second problem in my menu whenever i saw something there is on top in the list of my menu a new blanc line, that happens everithime i looked at somethin, i have now 5 blank lines on top in my menu.

Very strange. I really do not know what to try to get it wrichgt

Can please someone help me?

**Comment by michaelarnauts** [comment]
@cometoluc this will be fixed in the next release that I will make soon. It has been fixed in this PR: https://github.com/add-ons/plugin.video.vtm.go/pull/327

**Comment by michaelarnauts** [comment]
@cometoluc you can get the updated version here: https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.3.2 . It will be in the Kodi repo soon.

Normally, the addon shouldn't use invalid cached items, but you can go to the VTM Go add-on Settings -> Expert and do a "Clear cache" there to be sure.

**Comment by Bart80-1** [comment]
Probably not directly related to this issue, but... the addon in my setup (RPi4,LibreElec 10.0.2) does not seem to get updated, I'm still on version 1.3.0+matrix.1. I tried reinstalling the addon, still get the 1.3.0. Also when I check for the available versions for the plugin (button "versions" in the plugin screen) I only see 1.3.0 ... Is it normal that it takes +- 5 days for an update to be pushed? Are there other ones with this issue?

**Comment by Bart80-1** [comment]
> Probably not directly related to this issue, but... the addon in my setup (RPi4,LibreElec 10.0.2) does not seem to get updated, I'm still on version 1.3.0+matrix.1. I tried reinstalling the addon, still get the 1.3.0. Also when I check for the available versions for the plugin (button "versions" in the plugin screen) I only see 1.3.0 ... Is it normal that it takes +- 5 days for an update to be pushed? Are there other ones with this issue?

Ok, I was able to solve it by forcing an update check in the Addon options (and possibly by playing around in the settings)... 
Addon seems to work nicely on first sight now ;) tx!

**Comment by cometoluc** [comment]
Hello,

i have a problem with the vtmgo addon again
when i go to my menu i get again the error

404 Client Error:Not found for url:
https=//lfvp-apidpgmedia.net/vtmgo/programs/........


i work on windows 7 32bit
last vtmgo versie 1.3.2+matrix.1
kodi versie 19.3(19.3.0)

Can someone please help me or send me to the correct post if this post is wrong
Best regards

**Comment by cometoluc** [comment]
again problems witth vtmg addon. No of the live channenls play, it only says VTMGO ERROR

ik werk op windows 732bit laatste
vtmgo versie 1.4++matrix.1
kodi versie 19.3(19.3.0)

**Comment by cometoluc** [comment]
Hello,   does anyoneheve he problems that the live channens don't play

thanks
k werk op windows 732bit laatste
vtmgo versie 1.4++matrix.1
kodi versie 19.3(19.3.0)
