### ISSUE TITLE
Vtm go addon doesn't launch

### ISSUE THREAD

**Issue by nicspep** [add-ons/plugin.video.vtm.go#375]
When starting the VTM GO addon it says 
"Addon stopt working"

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version:
 - Kodi version:
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

**Comment by badoneti** [comment]
Same here
`2024-02-21 20:18:21.175 T:222814   error <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/catalog/mylist
2024-02-21 20:18:21.190 T:813     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/catalog/mylist) failed
2024-02-21 20:18:22.792 T:846      info <general>: JSONRPC Server: New connection added
2024-02-21 20:18:38.764 T:222824   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 22, in index
                                                       if auth.get_tokens():
                                                          ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 145, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh', data={
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh
                                                   -->End of Python script error report<--
`

**Comment by frankdpGH** [comment]
Same here, seems there was another update from the app....

**Comment by cometoluc** [comment]
i have the same problem.

ik krijg vtmgo weer niet opgestart. Totaal niet


ik werk op windows 732bit laatste
vtmgo versie 1.4.3++matrix.1
kodi versie 19.3(19.3.0)

**Comment by koenleys** [comment]
in resources/lib/vtmgo/util.py, change line 20 and 21 to
`    'User-Agent': 'VTM_GO/15.231023 (be.vmma.vtm.zenderapp; build:18041; Android 23) okhttp/4.11.0',
    'x-app-version': '15',`
That should fix the problem

**Comment by cometoluc** [comment]
can someone please make a new addon because is dont understand anything from coding. Pleeeese

**Comment by cobragerard** [comment]
Thanks, it is working again!!!

**Comment by PeterCloet** [comment]
Same issue here. Will try the patch in the code tonight.
Will anyone be realsing an update of the plugin?

**Comment by Nick4-1** [comment]
> can someone please make a new addon because is dont understand anything from coding. Pleeeese

This is really easy to do it yourself.
If someone else has to do it, how are you gonna get it then.

Just use the zipfile with the latest release, open it, navigate to the folder as @koenleys described and edit that file with just a basic text editor as mentioned.
Save it and install it again on your mediaplayer.

**Comment by michaelarnauts** [comment]
> Same issue here. Will try the patch in the code tonight. Will anyone be realsing an update of the plugin?

If you can make the merge request, I can push the release to Kodi :)

**Comment by mrtreg** [comment]
> > Same issue here. Will try the patch in the code tonight. Will anyone be realsing an update of the plugin?
> 
> If you can make the merge request, I can push the release to Kodi :)

I have a branch ready, but cannot push to this project. Can you give me the right to do so please? Thx! :)

**Comment by michaelarnauts** [comment]
> > > Same issue here. Will try the patch in the code tonight. Will anyone be realsing an update of the plugin?
> > 
> > 
> > If you can make the merge request, I can push the release to Kodi :)
> 
> I have a branch ready, but cannot push to this project. Can you give me the right to do so please? Thx! :)

You need to fork this project and create a new branch there, then you can open a merge request on this project.

**Comment by lebeno** [comment]
I tried the fix but the plugin is still not working. Even after clearing the plugin cache via Expert settings, I get error `'NoneType' object is not iterable` when browsing anything in the catalog.

```
2024-02-23 17:32:16.433 T:1984     info <general>: Skipped 36 duplicate messages..
2024-02-23 17:32:16.433 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is valid
2024-02-23 17:32:16.434 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.434 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://lfvp-api.dpgmedia.net/VTM_GO/tokens/refresh: {'lfvpToken': 'eyJhbGciOiJIUzUxMiJ9.....'}
2024-02-23 17:32:16.501 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.501 T:1984     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "POST /VTM_GO/tokens/refresh HTTP/1.1" 200 484
2024-02-23 17:32:16.502 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.502 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"lfvpToken":"eyJhbGciOiJIUzUxMiJ9......","expiresIn":28800,"hashedAccountId":"...","accountId":"...626ea6","userInfo":null}
2024-02-23 17:32:16.502 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.502 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending GET https://lfvp-api.dpgmedia.net/VTM_GO/profiles
2024-02-23 17:32:16.587 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.587 T:1984     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /VTM_GO/profiles HTTP/1.1" 200 683
2024-02-23 17:32:16.588 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.588 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"profiles":[{"id":"c82d80a7-bb3c-4ab3-a3d8-9213390c7fc4","name":"KKS","gender":"UNDEFINED","birthDate":"1973-08-17","mainProfile":true,"kidsProfile":false,"color":{"id":1001,"start":"#64d8e3","end":"#094aa9"}}],"constraints":{"colors":[{"id":1001,"start":"#64d8e3","end":"#094aa9"},{"id":1002,"start":"#4DFF76","end":"#2BA648"},{"id":1003,"start":"#0243FF","end":"#0E00B0"},{"id":1004,"start":"#831CFA","end":"#46098C"},{"id":1005,"start":"#FFB24D","end":"#FFDF42"},{"id":1006,"start":"#FF4DD5","end":"#B830A8"},{"id":1007,"start":"#FFB002","end":"#FD7801"},{"id":1008,"start":"#FF0257","end":"#A40037"}],"mainProfileMinimumAge":13,"maximumAdultProfileCount":2,"maxProfileCount":5}}
2024-02-23 17:32:16.590 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.590 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending GET https://lfvp-api.dpgmedia.net/VTM_GO/storefronts/main/detail/b2b0b4d7-c08e-4fb9-98d0-f6b0ca839d3e
2024-02-23 17:32:16.682 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.682 T:1984     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /VTM_GO/storefronts/main/detail/b2b0b4d7-c08e-4fb9-98d0-f6b0ca839d3e HTTP/1.1" 200 6533
2024-02-23 17:32:16.683 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.683 T:1984     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"abroad":false,"row":{"id":"b2b0b4d7-c08e-4fb9-98d0-f6b0ca839d3e","metaData":{"provider":"APP","campaignId":null},"title":"Moet je nu zien","rowType":"SWIMLANE_LANDSCAPE","teasers":[{"title":"Blind Gesprongen","target":{"type":"PROGRAM","id":"821fbdf1-4f9d-41b3-962c-f67b626132db","name":"Blind Gesprongen"},"imageUrl":"https://images1.persgroep.net/rcs/8xD7oceJIVcFVSBbPxhghIGEQiY/diocontent/240877014/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8","blockedFor":null,"overlayImageUrl":null,"comingSoon":null},{"title":"The Voice van Vlaanderen","target":{"type":"PROGRAM","id":"eabbef99-d3d1-4259-83f1-499dfe1bf092","name":"The Voice van Vlaanderen"},"imageUrl":"https://images3.persgroep.net/rcs/4Sbl7QGEZoWnm1r3TUYVIJf6kyc/diocontent/240596870/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8","blockedFor":null,"overlayImageUrl":null,"comingSoon":null},{"title":"The Voice Comeback Stage","target":{"type":"PROGRAM","id":"a2f5126c-8993-4a4f-b585-62b006a5d929","name":"The Voice Comeba
2024-02-23 17:32:16.683 T:1984     info <general>: Skipped 2 duplicate messages..
2024-02-23 17:32:16.683 T:1984    error <general>: [plugin.video.vtm.go] [resources.lib.modules.catalog] 'NoneType' object is not iterable
``

**Comment by cometoluc** [comment]
Dat probleem had ik al de laatste maanden. 

Hoop dat u er snel een addon van kunt maken want de code in github daar ken ik niets van 

Mvg 
Luc Van [ ***@***.*** | devoorde ] 
0477218049 
Veluwestraat 65 
2800 mechelen Belgie 
0477218049 


Van: "Michaël Arnauts" ***@***.***> 
Aan: "add-ons" ***@***.***> 
Cc: "Luc Van devoorde" ***@***.***>, "Comment" ***@***.***> 
Verzonden: Vrijdag 23 februari 2024 17:49:19 
Onderwerp: Re: [add-ons/plugin.video.vtm.go] Vtm go addon doesn't launch (Issue #375) 





I also think more changes are needed. The test also seem to fail on starting live TV.

**Comment by Nick4-1** [comment]
> I also think more changes are needed. The test also seem to fail on starting live TV.

Hi @michaelarnauts, FYI over here everything works like before (live, on-demand) by changing only those 2 entries with the user agent. (LibreELEC 11.0.6 on RPi4)

**Comment by CoderPupil** [comment]
Working fine again on LibreELEC Generic after changing "util.py", but only after doing the update from LibreELEC 11.0.5 to 11.0.6.

**Comment by coreflake1** [comment]
Changing "util.py" worked for me as well on LibreELEC 11.0.6, raspi 4 
Both livestreams and VOD are working again.

**Comment by michaelarnauts** [comment]
Thanks for verifying. The streamz addon probably needs the same change.

I'll look later why the tests are failing.

I hope to find time to make a release on a few days.

**Comment by cometoluc** [comment]
Hello Michel

Is there a new addon olease ?and where? or is this wheree you still have to work?

**Comment by Bradtus** [comment]
> Hello Michel
> 
> Is there a new addon olease ?and where? or is this wheree you still have to work?

you should really remove your post that has your full name, adress and phone number visible

**Comment by cometoluc** [comment]
Ok thanks. Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bradtus ***@***.***> Datum: 24/02/2024  18:07  (GMT+01:00) Aan: "add-ons/plugin.video.vtm.go" ***@***.***> Cc: cometoluc ***@***.***>, Comment ***@***.***> Onderwerp: Re: [add-ons/plugin.video.vtm.go] Vtm go addon doesn't launch (Issue #375) 

Hello Michel
Is there a new addon olease ?and where? or is this wheree you still have to work?

you should really remove your post that has your full name, adress and phone number visible

**Comment by pejeio** [comment]
> Working fine again on LibreELEC Generic after changing "util.py", but only after doing the update from LibreELEC 11.0.5 to 11.0.6.

Hi @CoderPupil, how do you update LibreELEC? I'm using Kodi on a Mac.

**Comment by michaelarnauts** [comment]
@pejeio I've fixed the object is not iterable issue and merged @mrtreg's API bump.

You can test the 1.4.4 release here: https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.4.4

Live TV won't probably work anymore on Kodi Matrix and earlier. We were using an older API there that was still compatible, but that API has been shut down.

Can you all please do a quick test and confirm that everything seems to be working again? I can push the update to the Kodi repo then.

**Comment by cometoluc** [comment]
Halo Michael. I Will see that i can install of the addon. Is it best to to disable the automatic upgrade in the addon? Best regards and youre time to help us auto troubbel Always Verzonden vanaf mijn Samsung GALAXY-S8 smartphone.
-------- Oorspronkelijk bericht --------Van: Michaël Arnauts ***@***.***> Datum: 26/02/2024  12:47  (GMT+01:00) Aan: "add-ons/plugin.video.vtm.go" ***@***.***> Cc: cometoluc ***@***.***>, Comment ***@***.***> Onderwerp: Re: [add-ons/plugin.video.vtm.go] Vtm go addon doesn't launch (Issue
  #375) 
@pejeio I've fixed the object is not iterable issue and merged @mrtreg's API bump.
You can test the 1.4.4 release here: https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.4.4
Live TV won't probably work anymore on Kodi Matrix and earlier. We were using an older API there that was still compatible, but that API has been shut down.
Can you all please do a quick test and confirm that everything seems to be working again? I can push the update to the Kodi repo then.

**Comment by cometoluc** [comment]
@michaelarnauts 

Hello for as far as i can see vtmgo works back also the menus, flmen.. with your addon. For me atlast 

Thanks again Is early yet but, i can miss some things 





Van: "Michaël Arnauts" ***@***.***> 
Aan: "add-ons" ***@***.***> 
Cc: "Luc Van devoorde" ***@***.***>, "Comment" ***@***.***> 
Verzonden: Maandag 26 februari 2024 12:47:43 
Onderwerp: Re: [add-ons/plugin.video.vtm.go] Vtm go addon doesn't launch (Issue #375) 





[ https://github.com/pejeio | @pejeio ] I've fixed the object is not iterable issue and merged [ https://github.com/mrtreg | @mrtreg ] 's API bump. 

You can test the 1.4.4 release here: [ https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.4.4 | https://github.com/add-ons/plugin.video.vtm.go/releases/tag/v1.4.4 ] 


Live TV won't probably work anymore on Kodi Matrix and earlier. We were using an older API there that was still compatible, but that API has been shut down. 

Can you all please do a quick test and confirm that everything seems to be working again? I can push the update to the Kodi repo then.

**Comment by lebeno** [comment]
After manually installing the ZIP it looks like the new version has fixed the problem. Thanks!

**Comment by pejeio** [comment]
After removing the add-on and installing from the ZIP and re-authenticating, everything works! Thank you so much @michaelarnauts! ❤️

**Comment by cobragerard** [comment]
On my W11 pc everything works fine with live tv but not on my my W10 installatiom.

**Comment by M4stakilla** [comment]
Hi,

Is it possible that the same issue is back? I already have v1.4.4 of the plugin installed and the code that koenleys suggested to replace, is already the same
